# Default Spark configuration settings
# These settings provide sensible defaults for most Spark applications

# Basic settings
spark:
  # Application metadata
  app:
    name: "${SPARK_APP_NAME:ImputedSalesAnalytics}"
    queue: "${SPARK_QUEUE:default}"
    
  # Core settings
  driver:
    memory: "${SPARK_DRIVER_MEMORY:4g}"
    maxResultSize: "${SPARK_DRIVER_MAXRESULTSIZE:4g}"
    cores: "${SPARK_DRIVER_CORES:2}"
    
  # Executor settings
  executor:
    instances: "${SPARK_EXECUTOR_INSTANCES:4}"
    cores: "${SPARK_EXECUTOR_CORES:2}"
    memory: "${SPARK_EXECUTOR_MEMORY:4g}"
    memoryOverhead: "${SPARK_EXECUTOR_MEMORY_OVERHEAD:1024}"  # MB
    
  # Memory management
  memory:
    fraction: 0.8
    storageFraction: 0.3
    
  # Shuffle settings
  shuffle:
    service:
      enabled: "${SPARK_SHUFFLE_SERVICE_ENABLED:true}"
    compress: "${SPARK_SHUFFLE_COMPRESS:true}"
    spill:
      compress: "${SPARK_SHUFFLE_SPILL_COMPRESS:true}"
    
  # Serialization
  serializer: "org.apache.spark.serializer.KryoSerializer"
  kryo:
    classesToRegister: ""
    registrationRequired: "${SPARK_KRYO_REGISTRATION_REQUIRED:false}"
    referenceTracking: "${SPARK_KRYO_REFERENCE_TRACKING:true}"
    
  # SQL settings
  sql:
    shuffle:
      partitions: "${SPARK_SQL_SHUFFLE_PARTITIONS:200}"
    caseSensitive: "${SPARK_SQL_CASE_SENSITIVE:false}"
    files:
      maxPartitionBytes: "${SPARK_SQL_FILES_MAX_PARTITION_BYTES:134217728}"  # 128MB
      openCostInBytes: "${SPARK_SQL_FILES_OPEN_COST_IN_BYTES:4194304}"  # 4MB
    
  # Dynamic allocation
  dynamicAllocation:
    enabled: "${SPARK_DYNAMIC_ALLOCATION_ENABLED:true}"
    executorIdleTimeout: "${SPARK_DYNAMIC_ALLOCATION_EXECUTOR_IDLE_TIMEOUT:60s}"
    cachedExecutorIdleTimeout: "${SPARK_DYNAMIC_ALLOCATION_CACHED_EXECUTOR_IDLE_TIMEOUT:infinity}"
    initialExecutors: "${SPARK_DYNAMIC_ALLOCATION_INITIAL_EXECUTORS:minExecutors}"
    minExecutors: "${SPARK_DYNAMIC_ALLOCATION_MIN_EXECUTORS:1}"
    maxExecutors: "${SPARK_DYNAMIC_ALLOCATION_MAX_EXECUTORS:100}"
    
  # Network settings
  network:
    timeout: "${SPARK_NETWORK_TIMEOUT:120s}"
    
  # I/O settings
  io:
    compression:
      codec: "${SPARK_IO_COMPRESSION_CODEC:snappy}"
      snappy:
        blockSize: "${SPARK_IO_COMPRESSION_SNAPPY_BLOCKSIZE:32k}"
